### ISSUE TITLE
adding new task opens existing task instead of newly created task

### ISSUE THREAD

**Issue by olafhering** [lharding/tasknc#41]
With tasknc b887688 creating a new task with 'a' opens an existing task in the editor, instead of opening the newly created task. One has leave the editor, scroll down in the list to 'new task' and edit it with 'e'.

**Comment by lharding** [comment]
Thank you for this - I haven't used the native 'add' feature in a bit and so didn't realize it was broken. Until I get around to fixing this (or someone opens a PR), here's what I've been doing instead:

In `~/.config/tasknc/config`:
```
unbind tasklist a
  bind tasklist  a  shell ~/.config/tasknc/promptadd
```

Content of `~/.config/tasknc/promptadd`:
```
#!/bin/bash

clear
read -e desc
task add "$desc"
```

I prefer this method because it doesn't require a roundtrip through an editor just to add a task. In general extension and configuration via scripting over inbuilt functionality is my roadmap for tasknc.
